# Dependabot will run on day 2 of each month at 01:41 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '41 1 2 * *'
    open-pull-requests-limit: 15
    assignees:
      - 'Sefina-DS'
    versioning-strategy: 'increase'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '41 1 2 * *'
    open-pull-requests-limit: 15
    assignees:
      - 'Sefina-DS'
